name: Build containers for prod & push to Dockerhub

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy-back-end:
    name: Build and deploy back-end
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./App/Back-end/tripbuddyc
          push: true
          tags: rathumbel/tripbuddyc-back:latest

  build-and-deploy-front-end:
    name: Build and deploy front-end
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./App/Front-end/tripbuddyc
          push: true
          tags: rathumbel/tripbuddyc-front:latest

  SSH-connection:
    name: Connect through SSH and execute script
    runs-on: ubuntu-latest
    needs: [build-and-deploy-back-end, build-and-deploy-front-end]
    
    steps:
      - name: SSH connection
        uses: fifsky/ssh-action@master
        with:
          command: |
            sudo docker-compose pull
            sudo docker-compose up -d
          host: ${{ secrets.VM_HOST }}
          user: rafaon98
          pass: ${{ secrets.VM_PASSWORD }}
    
